        var images = {
    1: [
        {   href: 'portfolio/real_prod/HEY_JULIA/1.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/2.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/3.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/4.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/5.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/6.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/HEY_JULIA/7.jpg',                
            title: null}        
    ],
    2: [
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/1.jpg',                
            title: null},
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/2.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/3.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/4.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/5.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/6.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/7.jpg',                
            title: null},  
        {   href: 'portfolio/real_prod/PUSS_IN_BOOTS/8.jpg',                
            title: null}
    ],
    3: [
        {   href : 'portfolio/real_prod/THE_OVERCOAT/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/10.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/11.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/12.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/13.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/14.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/15.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/16.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/17.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/18.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/19.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/20.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/21.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_OVERCOAT/22.jpg',                
            title : null   }
    ],
    4: [
        {   href : 'portfolio/real_prod/JORNEY_WITH/1.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/2.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/3.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/4.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/5.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/6.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/7.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/8.jpg',                
            title : null},
        {   href : 'portfolio/real_prod/JORNEY_WITH/9.jpg',                
            title : null}
    ],
    5: [
        {   href : 'portfolio/real_prod/FATHER/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/FATHER/7.jpg',                
            title : null   }
    ],
    6: [
        {   href : 'portfolio/real_prod/THE_CUTCHER/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/10.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/11.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/12.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/14.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/15.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/16.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/17.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/18.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_CUTCHER/19.jpg',                
            title : null   }
    ],
    7: [
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/THE_LITTLE_HORSE/10.jpg',                
            title : null   }
    ],
    8: [
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/10.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/11.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/ACCIDENTAL_DEATH/12.jpg',                
            title : null   }
    ],
    9: [
        {   href : 'portfolio/real_prod/HEDDA_GABLER/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/10.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/11.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/12.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/13.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/14.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/15.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/16.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/17.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/18.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/19.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/20.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/21.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/22.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/23.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/24.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/25.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/26.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/27.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/28.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/HEDDA_GABLER/29.jpg',                
            title : null   }
    ],
    10: [
        {   href : 'portfolio/real_prod/EVEN_A_WISE/1.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/2.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/3.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/4.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/5.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/6.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/7.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/8.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/9.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/10.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/11.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/12.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/13.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/14.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/15.jpg',                
            title : null   },
        {   href : 'portfolio/real_prod/EVEN_A_WISE/16.jpg',                
            title : null   }
    ]
};

$(".open_fancybox").click(function() {
    $.fancybox.open(images[ $(this).index() + 1], {
        padding : 0
    });
    
    return false;
});
