        var images = {
    1: [
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/1.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/2.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/3.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/4.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/5.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/6.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/7.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/8.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/9.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/10.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/11.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/12.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/13.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/14.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/15.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/16.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/17.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/18.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/19.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/20.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/21.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/22.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/23.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MASTER_AND_MARGARITA/24.jpg',                
            title : null   }
    ],
    2: [
        {   href: 'portfolio/scen_proj/THE_HEAD/1.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/2.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/3.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/4.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/5.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/6.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/7.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/8.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THE_HEAD/9.jpg',                
            title: null}       
    ],
    3: [
        {   href : 'portfolio/scen_proj/MERRY_WIVES/1.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MERRY_WIVES/2.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MERRY_WIVES/3.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MERRY_WIVES/4.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/MERRY_WIVES/5.jpg',                
            title : null   }
    ],
    4: [
        {   href : 'portfolio/scen_proj/THREE_SISTERS/1.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THREE_SISTERS/2.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THREE_SISTERS/3.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THREE_SISTERS/4.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THREE_SISTERS/5.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THREE_SISTERS/6.jpg',                
            title : null   }
    ],
    5: [
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/1.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/2.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/3.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/4.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/5.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/6.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/7.jpg',                
            title: null},  
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/8.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/9.jpg',                
            title: null},
        {   href: 'portfolio/scen_proj/THREE_FAT_MEN/10.jpg',                
            title: null}
    ],
    6: [
        {   href : 'portfolio/scen_proj/THE_BIRDS/1.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/2.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/3.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/4.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/5.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/6.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/7.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/8.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/9.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/10.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/11.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/12.jpg',                
            title : null   },
        {   href : 'portfolio/scen_proj/THE_BIRDS/13.jpg',                
            title : null   }
    ],
    7: [
        {   href : 'portfolio/scen_proj/FLYING_DUTCHMAN/1.jpg',                
            title : null   }
    ],
    8: [
        {   href : 'portfolio/scen_proj/FALSTAFF/1.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/2.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/3.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/4.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/5.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/6.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/7.jpg',                
            title : null},
        {   href : 'portfolio/scen_proj/FALSTAFF/8.jpg',                
            title : null}
    ]
};

$(".open_fancybox").click(function() {
    $.fancybox.open(images[ $(this).index() + 1], {
        padding : 0
    });
    
    return false;
});
